// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgJXJIPvxdhB5gDKQSUlCnE1i-9MoTeaA',
    appId: '1:1056774929530:web:6e5c2fd3fb887252adcfc3',
    messagingSenderId: '1056774929530',
    projectId: 'vndor-e5506',
    authDomain: 'vndor-e5506.firebaseapp.com',
    storageBucket: 'vndor-e5506.firebasestorage.app',
    measurementId: 'G-693S109F7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfFt-O5rGpYk6Hoq6hI-t2DOkZmEm5VWk',
    appId: '1:1056774929530:android:ccf0311ea7215f7eadcfc3',
    messagingSenderId: '1056774929530',
    projectId: 'vndor-e5506',
    storageBucket: 'vndor-e5506.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZfFUSfnYOVXaZ6yTcqT8_d8FqQS9IHzA',
    appId: '1:1056774929530:ios:537c4e1143d037afadcfc3',
    messagingSenderId: '1056774929530',
    projectId: 'vndor-e5506',
    storageBucket: 'vndor-e5506.firebasestorage.app',
    iosBundleId: 'com.example.vndor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZfFUSfnYOVXaZ6yTcqT8_d8FqQS9IHzA',
    appId: '1:1056774929530:ios:537c4e1143d037afadcfc3',
    messagingSenderId: '1056774929530',
    projectId: 'vndor-e5506',
    storageBucket: 'vndor-e5506.firebasestorage.app',
    iosBundleId: 'com.example.vndor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgJXJIPvxdhB5gDKQSUlCnE1i-9MoTeaA',
    appId: '1:1056774929530:web:dee3362de916f25eadcfc3',
    messagingSenderId: '1056774929530',
    projectId: 'vndor-e5506',
    authDomain: 'vndor-e5506.firebaseapp.com',
    storageBucket: 'vndor-e5506.firebasestorage.app',
    measurementId: 'G-8BWLHFM5SN',
  );
}
